# Generated by Django 5.0.6 on 2024-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
